export const DONATES_KEY = 'donates'
export const CREATE_DONATE_KEY = 'create donate'
export const UNIQUE_ROLES_KEY = 'unique roles'
export const ROOM_CONTENT_KEY = 'room content'
export const ONLINE_OPTION_KEY = 'online options'
export const CREATE_ONLINE_OPTION_KEY = 'create online option'