-- AlterTable
ALTER TABLE "editor_badges" ALTER COLUMN "translateX" SET DEFAULT 0,
ALTER COLUMN "translateX" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "translateY" SET DEFAULT 0,
ALTER COLUMN "translateY" SET DATA TYPE DOUBLE PRECISION;

-- AlterTable
ALTER TABLE "editor_widgets" ALTER COLUMN "translateX" SET DEFAULT 0,
ALTER COLUMN "translateX" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "translateY" SET DEFAULT 0,
ALTER COLUMN "translateY" SET DATA TYPE DOUBLE PRECISION;
